### ISSUE TITLE
Right to Left Middle Eastern

### ISSUE THREAD

**Issue by brilliu** [Jefferson49/joomla4_plugin_sexy_polling#51] opened 2023-10-09 11:08 UTC
Hi, Thank you for the amazing Sexy Polling Joomla Extension, it's just fab.
I am having issues with Right to Left text appearing as left to right.
Thank you

**Comment by Jefferson49** [comment] 2023-10-09 12:34
Welcome to the plugin and thank you for reporting the issue!

Until now, I have no experience with right to left text. On first sight, I see two options:
+ Use font stettings for templates (see screenshot below). You can set "Poll Name Text Align" and "Answers Text Align" to "right. However, seemingly "Answers Text Align" does not react on the setting. Unfortunatelly, these kind of settings are not available for all texts/fonts.
+ If you have some know-how about css formating, you might want to change the css settings in the following file: joomla\components\com_sexypolling\assets\css\main.css. You can use the developer tools of your browser and identify the css classes of the text objects you want to change. If you know the css class of the object, you can change the css settings in main.css

![Poll name text align](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/81484983/3d0fcaea-b447-460b-b830-4eef29c43d73)

**Comment by brilliu** [comment] 2023-10-09 12:54
Hi, thank you for the swift reply.
Answers Text Align = right does not do anything.
I have some knowledge of CSS, will try to do that.
The problem it is creating is that I can't control the order of questions, 1, 2 ,3 4, 5 etc...
you can see it in the attached screen
![2023-10-09_13-52-31](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/66337669/917dbf61-1059-4b11-9435-808afb388575)
shot

**Comment by Jefferson49** [comment] 2023-10-09 19:01
I also do not understand why the first 2 answers are not ordered properly. Starting from the third answer, everything from "01/" up to "19/" seems to be o.k. 

I checked in the code and the ordering seems to be performed by a database query: 
`ORDER BY sexy_answers.name
`

You could use **phpMyAdmin** to check the answers in the database. Open the  "[prefix]**_sexy_answers**" table with phpMyAdmin and check the "name" column. Try to sort the data according to the "name" column and check if you can find some explaination for the ordering.

**Comment by Jefferson49** [comment] 2023-10-12 18:09
> Answers Text Align = right does not do anything.

I was able to identify the root cause and fixed it in the code. The bugfix will be available with the next release. 

However, I found out that the bug was only in the template configuration animation. If you save the changes in the template, the "Answers Text Align" setting will be saved properly and the new text alignment is shown in the site module. Therefore, you can use the feature also with the existing plugin version.

**Comment by Jefferson49** [comment] 2023-10-12 18:10
Fixed with [8eeb9df](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/commit/8eeb9df77f09e2a6b1488746b48bddd9d991ab8d)

**Closed as completed by Jefferson49** 2023-10-12 18:10 UTC
