### ISSUE TITLE
Multiple Votes Cast Even When Disabled?

### ISSUE THREAD

**Issue by Konsider** [Jefferson49/joomla4_plugin_sexy_polling#108] opened 2024-11-04 07:04 UTC
Hopefully this will be the last time I will be posting 😊

It seems it is possible for people to cast multiple votes simply by refreshing the page?

I have max votes set to 1. I have “Additional Checkings” enabled which should stop multiple votes based on IP? I have tested multiple browers. I have tried different IPs.

As soon as the page is refreshed, it’s possible to cast another vote. I must be doing something wrong, as this would render the whole plugin pretty much useless if people are able to spam it?

**Comment by Jefferson49** [comment] 2024-11-05 20:11
> As soon as the page is refreshed, it’s possible to cast another vote. I must be doing something wrong, as this would render the whole plugin pretty much useless if people are able to spam it?

There is a workshare between JavaScript, which runs in the browser and PHP, which runs on the server. The message that voting is rejected is managed by JavaScript in the browser. There is an issue with the JavaScript code that it only shows the rejection message until the browser is refreshed. Afterwards, JavaScript does not reject the vote and the vote is handed over to the PHP code on the server. If the IP address is known and has already voted, the vote is rejected by the PHP code.

Can you check in the Sexypolling backend in the votes area if you get new votes for existing IP addresses? You can see the IP addresses of the existing votes. It should not be able to get a new vote accepted for an existing IP.

I agree that the behavior is confusing for the user, because it looks like the vote is accepted, although it is not. Regarding JavaScript and refreshing,  there is a simular issue in #67. Unfortunately, it is difficult to solve.

**Comment by Konsider** [comment] 2024-11-05 21:02
You're absolutely correct. It just 'appears' like the user can vote again if the page is refreshed, but it doesn't actually count towards the vote. So, that's good :)

It would be great if you could somehow figure out how to get the JavaScript to recognise this too. It's certainly quite confusing if it looks like multiple votes can be cast. Maybe giving the code to ChatGPT might result in some ideas :)

I suppose it's always going to be tricky to completely restrict users from multiple votes, as they can obviously still use a proxy to bypass it. And cookies can just be cleared. I wonder what the ultimate solution to it all would be. Certainly not straightforward.

As always, thanks again for your comprehensive answer.

**Comment by Jefferson49** [comment] 2024-11-09 05:32
I could identify the root cause for this behavior. Surprisingly, there was a bug if using IPv6 ip addresses.

Will be fixed in the next release.

**Closed as completed** 2024-11-09 05:32 UTC
Labels: bug, Joomla 4, Joomla 3, Joomla 5
