### ISSUE TITLE
Error installing component: "TEXT, GEOMETRY or JSON column 'country' can't have a default value"

### ISSUE THREAD

**Issue by MacNaught0n** [Jefferson49/joomla4_plugin_sexy_polling#46] opened 2023-04-23 18:23 UTC
Receiving Error when installing joomla_plugin_sexypolling_reloaded_v4.1.7.zip into Joomla 4.3.0
BLOB, TEXT, GEOMETRY or JSON column 'country' can't have a default value

**Comment by Jefferson49** [comment] 2023-04-23 19:27
Thank you for reporting the issue!

Was this a complete new install in 4.3.0 or did you upgrade from an earlier plugin version or from the former Sexy Polling plugin?

**Comment by Jefferson49** [comment] 2023-04-23 21:03
I tried to reproduce with a new install on my 4.3.0 system. However, I did not get an error message. 

Additional questions:
+ Did you get the error during installation or after installation while using the plugin?
+ Can you activate Joomla debugging (Global configuration => System => Debug => Debug System) and try to catch a more detailed error message (while installing the plugin)? If possible, please post the complete error stack trace or attach it as a text file

**Comment by MacNaught0n** [comment] 2023-04-24 18:32
Jefferson,



Thanks for your prompt reply.

This is a new install. 

I had SexyPoll when the site was J3.x but it hung up when I did the J3.x -> J4.x conversion so I uninstalled it.

 

It does not successfully install.

I have attached a screenshot of the install results & a FPA report.

 

 



-------------------------------------------------------
Michael S. "Mac" Miller

Webmaster – Bengalhome Enterprises

www.bengalhome.com <http://www.bengalhome.com/> 

***@***.*** ***@***.***> 
(574) 440-0076


Notice of Confidentiality:
The information included and/or attached
in this electronic mail transmission may
contain confidential or privileged information
and is intended for addressee only.
Any unauthorized disclosure, reproduction,
distribution is not allowed without prior written
permission from the author.  
If you have received this message in error, 
please notify the sender and delete the message
without disclosure.

**Comment by MacNaught0n** [comment] 2023-04-24 18:57
Just realized I missed one of the screen shots

 

Mac

**Comment by Jefferson49** [comment] 2023-04-25 04:40
Thank you for providing more information. I guess you answered with email. However, I am not sure if I can see all the information you provided, e.g. the screenshot is not visible to me. Maybe, you can check with a browser if everything you provided is visible.

What I can see is that you are using MySQL version 5.7.23-23, which was released 2018-07-27: https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-23.html

With an internet search, I found that MySQL did not support to set default values for text columns in MySQL versions before 2018-10-22: 
https://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql

This could explain why you get the error message  "BLOB, TEXT, GEOMETRY or JSON column 'country' can't have a default value"

In the mentioned source, I found the following explaination:
"The main reason is the flag STRICT_TRANS_TABLES for sql_mode setting. if a value is not specified in INSERT statement for TEXT datatype column and if the flag exist in the sql_mode setting then MySQL is reporting an error; and if the flag doesn't exist then MySQL is only reporting a warning and inserts the record.

So, to prevent this error, one can remove the STRICT_TRANS_TABLES from sql_mode setting of MySQL. (He my need to reset the mode to the previous value if it can affect other operations on the database.)"

Therefore, to get around this issue, you have two options:
+ Upgrade your MySQL database to a version after 2018-10-22
+ Change the **sql_mode** variable of your MySQL settings

Since changing the variable might also encounter side effects, updating the MySQL version would be prefered.

For changing the **sql_mode** variable, the following steps are proposed in the source above:
+ "If you have root access and are using phpMyAdmin, go to the main page (click the phpMyAdmin logo), go to the Variables tab, find the sql_mode variable, and click Edit. – "
+ "remove the STRICT_TRANS_TABLES from sql_mode setting"
+ Alternatively: set sql_mode='MYSQL40'. You can also run a MySQL query, e.g. in phpMyAdmin: SET @@global.sql_mode='MYSQL40'

Before trying this, you should backup your database and database settings. Also copy and save the previous/current setting of the **sql_mode** variable in order to roll back in case of problems.

**Comment by nfbauti** [comment] 2023-04-26 21:04
Cordial saludo, en mi caso el componente funcionó correctamente.

Quisiera proponer que en la opción de respuestas por ejemplo, sea posible subir imagenes en ves de apuntarlas a enlaces externos, por ejemplo, si hago una encuesta con los mejores jugadores de fútbol, que la respuesta permita subir la imagen del jugador y al terminar la encuesta eliminarla sin dejar basura.

Gracias por tenerlo presente, por lo demás, excelente complemento de encuestas para nuestro amado Joomla 4.

**Comment by Gimopa** [comment] 2023-10-08 18:23
it is not possible to install plugin on joomla 4.3.4

![image](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/94612587/0ac3f3fe-122c-4401-99d3-e97e1432586e)

![image](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/94612587/32adde2f-968d-4327-9fb1-9576e0953d46)

**Comment by Jefferson49** [comment] 2023-10-08 18:44
Thank you for reporting the issue!

Can you check and provide your database version?
The error "TEXT, GEOMETRY or JSON column 'country' can't have a default value seems to be related to the database version.

Plugin releases starting from v4.1.7 need a MySQL version of 5.7.24 (8.0.13) or later.
For MySQL versions earlier than 5.7.24, the former plugin release v4.1.6 can be used.

**Comment by Jefferson49** [comment] 2023-10-08 19:46
Another point might be the PHP version. Until recently, there was a recomendation to use PHP 8.1 for Joomla 4.3. I have just checked that it seems to be 8.2 nowadays. However, my own Joomla 4.3.4 installation does not work properly with PHP 8.2. Since my Joomla site does not work with PHP 8.2, I can not provide any statements about sexypolling_reloaded and PHP 8.2.

If you have the chance to choose between PHP versions on your server, I recommend to try PHP 8.1

**Comment by Gimopa** [comment] 2023-10-09 08:18
I've the following configuration:
[PHP --> 8.2](phpversion: 8.2.9)
dbversion: 8.0.26
version: Joomla! 4.3.4 Stable

I tried thee release v4.1.7, but it isn't work

I don't have the possibility to switch to PHP8.1 --> I can choise PHP8.0 or PHP8.2.

Do you have others suggestion?

**Comment by Jefferson49** [comment] 2023-10-09 09:26
Thanks for the additional information. Since your database version (8.0.26) is newer than 8.0.13, the database should be o.k.

> Do you have other suggestions?

+ You can switch to PHP 8.0. For Joomla and the plugin, this should also be o.k.; maybe a little bit lower performance than 8.2. It would be interesting for me, if another PHP version would fix the issue, because until now it only showed up with old database versions.
+ You can try to install the earlier plugin version v4.1.6. The "can't have a default value" type of errors did not show up in v4.1.6

**Comment by Gimopa** [comment] 2023-10-09 10:01
Thanks for your suggestion. I tried to install the version 4.1.6 and it is work fine.
Next 2 question: 
1- Now, can I install also version 4.1.7 or it is in conflict with version v4.1.6?
2- the installation of v4.1.7 substitute v4.1.6 or create another plugin?

thanks for now

**Comment by Jefferson49** [comment] 2023-10-09 11:16
>1- Now, can I install also version 4.1.7 or it is in conflict with version v4.1.6?

You can install v4.1.7. However, you will probably get the same error again. In general, you can switch between the versions.

>2- the installation of v4.1.7 substitute v4.1.6 or create another plugin?

The versions substitute each other and use the existing database. Plugin v4.1.7 will change some settings in the database, but the changes should be backwards compatible to v4.1.6.

The only thing, where I do not have an answer yet, are future versions. At the moment, it looks like I will have to support two different branches, because otherwise the v4.1.6 will have no successor.

**Comment by Jefferson49** [comment] 2023-10-09 11:21
> You can install v4.1.7. However, you will probably get the same error again.

If you have some time for a short test, it would be interesting for me, if you get the error again if installing v4.1.7. Indeed, I have no experience yet, what happens in this case. Maybe, there is a chance that it is working.

**Comment by Gimopa** [comment] 2023-10-09 14:52
I tried install the version 4.1.7 on top of v4.1.6 but the issue still show up

**Comment by Jefferson49** [comment] 2023-10-09 20:47
> I tried install the version 4.1.7 on top of v4.1.6 but the issue still show up

Thanks for testing. I was now able to fix some issues in my Joomla 4.3.4 installation and got it running with PHP 8.2. I can install the sexy_polling plugin v4.1.7 without any errors. Therefore, I think the behavior is not related to the PHP version but to the database configuration.

Like posted above, some background can be found here:
https://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql

However, it is difficult to sort.

**Comment by Jefferson49** [comment] 2023-10-10 04:32
> I tried install the version 4.1.7 on top of v4.1.6 but the issue still show up

After further considerations, I think I have found the root cause of the issue in the code. I have created a beta version (v4.1.8beta) with a bugfix. It would be nice, if you could test it. If it is working and fixes the issue, I will publish it as a new release.

[com_sexypolling_v4.1.8beta.zip](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/files/12852758/com_sexypolling_v4.1.8beta.zip)

**Comment by Gimopa** [comment] 2023-10-10 07:18
I tried the v4.1.8beta, but it isn't working.

**Comment by Gimopa** [comment] 2023-10-10 07:36
Other question for me importat:
is it not possible to show all surveys?
In module i saw that is possible only show 1 survey for time



![image](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/94612587/f4225e30-73db-466c-9d0f-85fedea29fc5)

**Comment by Jefferson49** [comment] 2023-10-10 08:06
> I tried the v4.1.8beta, but it isn't working.

Would it be possible for you to switch on debugging with maximum error reporting and post the detailed error messages after failed installation?
+ Global configuration -> System -> Debug System -> Yes
+ Global configuration -> Server -> Error Reporting -> Maximum

**Comment by Jefferson49** [comment] 2023-10-10 08:09
> is it not possible to show all surveys?
> In module i saw that is possible only show 1 survey for time

You need to create one site module for each poll you want to show. After installation, there is only one default site module created. Just add more site modules with the "New" button and assign different polls to the different site modules.

**Comment by Jefferson49** [comment] 2023-10-10 17:02
> I tried the v4.1.8beta, but it isn't working.

I improved the bugfix and created a second beta version. It would be nice if you could test once more:

[com_sexypolling_v4.1.8beta2.zip](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/files/12859884/com_sexypolling_v4.1.8beta2.zip)

I guess it only works for a new install. Therefore, you would need to de-install an existing plugin first. **However, this will loose the data of the plugin**. If you want to keep the data, you could use phpMyAdmin and create a backup of all the sexy_XYZ tables first.

**Comment by Jefferson49** [comment] 2023-10-10 18:41
> is it not possible to show all surveys?

I just recognized that you can show all polls, if you select "polls" ("Sondaggi"), like you did in the screenshot above. In this case, the selection of any single poll in the drop down menu has no effect. However, you can (but dont have to) choose a category. In this case, all polls which belong to the category are shown.

Simularly, if you choose to show a single poll ("Sondaggio singulo"), the category has no effect and the drop down menu selects the poll.

**Comment by Jefferson49** [comment] 2023-11-06 15:49
Just recently, I published a new release [v5.0.0](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/releases/tag/v5.0.0), which is avoiding installation errors of the tpye "column 'country' can't have a default value". Maybe, you can check if the new version also solves the issues you described.

**Comment by Jefferson49** [comment] 2023-11-11 10:53
Hopefully fixed with v5.0.0

**Closed as completed by Jefferson49** 2023-11-11 10:53 UTC
Labels: MySQL version
